Home:
    path: /
    controller: App\Health\Infrastructure\Api\HealthController
    methods: [GET]

Dispenser:
    prefix: /api/dispensers
    resource: ../src/Dispensers/Infrastructure/Api/routes.yaml
    trailing_slash_on_root: false

Usage:
    prefix: /api/usages
    resource: ../src/Usages/Infrastructure/Api/routes.yaml
    trailing_slash_on_root: false

Health:
    prefix: /api/health
    resource: ../src/Health/Infrastructure/Api/routes.yaml
    trailing_slash_on_root: false

kernel:
    resource: ../src/Kernel.php
    type: annotation
